// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/apriliantocecep/ordent-restapi-artikel/app/Http/Controller"
	"github.com/apriliantocecep/ordent-restapi-artikel/app/Http/Middleware"
	"github.com/apriliantocecep/ordent-restapi-artikel/app/Http/Repository"
	"github.com/apriliantocecep/ordent-restapi-artikel/app/Http/Service"
	"github.com/apriliantocecep/ordent-restapi-artikel/config"
	"github.com/apriliantocecep/ordent-restapi-artikel/routes"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from server.go:

func InitializedServer(configOptions config.ConfigOptions) *gin.Engine {
	userRepositoryImpl := repository.NewUserRepositoryImpl()
	configConfig := config.NewConfig(configOptions)
	db := config.NewDB(configConfig)
	jwtWrapper := config.NewJwtWrapper(configConfig)
	authServiceImpl := service.NewAuthServiceImpl(userRepositoryImpl, db, configConfig, jwtWrapper)
	authMiddlewareConfig := middleware.NewAuthMiddlewareConfig(authServiceImpl)
	homeControllerImpl := controller.NewHomeControllerImpl()
	authControllerImpl := controller.NewAuthControllerImpl(authServiceImpl)
	articleRepositoryImpl := repository.NewArticleRepositoryImpl()
	articleServiceImpl := service.NewArticleServiceImpl(articleRepositoryImpl, db)
	articleControllerImpl := controller.NewArticleControllerImpl(articleServiceImpl)
	engine := routes.RegisterRoutes(authMiddlewareConfig, homeControllerImpl, authControllerImpl, articleControllerImpl)
	return engine
}

// server.go:

var homeSet = wire.NewSet(controller.NewHomeControllerImpl, wire.Bind(new(controller.HomeController), new(*controller.HomeControllerImpl)))

var authSet = wire.NewSet(repository.NewUserRepositoryImpl, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)), service.NewAuthServiceImpl, wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)), controller.NewAuthControllerImpl, wire.Bind(new(controller.AuthController), new(*controller.AuthControllerImpl)))

var articleSet = wire.NewSet(repository.NewArticleRepositoryImpl, wire.Bind(new(repository.ArticleRepository), new(*repository.ArticleRepositoryImpl)), service.NewArticleServiceImpl, wire.Bind(new(service.ArticleService), new(*service.ArticleServiceImpl)), controller.NewArticleControllerImpl, wire.Bind(new(controller.ArticleController), new(*controller.ArticleControllerImpl)))

var configSet = wire.NewSet(config.NewConfig, config.NewDB, config.NewJwtWrapper)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddlewareConfig)
